server:
  port: 7003
  
eureka:
  instance:
    hostname: Eureka7003 #eureka服务端的实例名称
  client: 
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://Eureka7001:7001/eureka,http://Eureka7002:7002/eureka