server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        
  type-aliases-package: com.hisin.springcloud.entities      
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
spring:
   application:
    name: microservicecloud-sysrole
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/webdb
    username: root
    password: root
    dbcp2:
      min-idle: 5                                           
      initial-size: 5                                       
      max-total: 5                                         
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-sysrole-8001
    prefer-ip-address: true
    
info:
  app.name: microservicecloud-sysRole
  company.name: www.hisin.com
  build.artifactId: $project.artifactId$
  build.version:  $project.version$
      
      